### ISSUE TITLE
Possible issue with denomination

### ISSUE THREAD

**Issue by asselstine** [steffenix/sushi-pooltogether#1]
In your SushiYieldSource [redeem function](https://github.com/steffenix/sushi-pooltogether/blob/722307052b72c4a2e716ce335d189d0fb073aaf9/contracts/SushiYieldSource.sol#L88) you're passing the redeemAmount directly:

```solidity
    function redeem(uint256 redeemAmount) public override returns (uint256) {
        // ...
        bar.leave(redeemAmount);
        // ...
   }
```

However, doesn't the SushiBar leave() function expect the denomination to be in xSushi?

The PrizePool always passes values in terms of the `token()`; so in your case the `SUSHI` token.  If SushiBar is expecting xSushi this could be a problem

**Comment by asselstine** [comment]
I see!  Yes that's not very clear.  I'll update the docs.

The `redeem()` function expects to receive the amount denominated in the `token()`, and in your case it will be `SUSHI`

**Comment by asselstine** [comment]
Well, I'll leave the issue open until it's resolved

**Comment by steffenix** [comment]
working on it immediately.

**Comment by steffenix** [comment]
Another feedback @asselstine ?

**Comment by asselstine** [comment]
LGTM

**Comment by steffenix** [comment]
@dangerousfood
