### ISSUE TITLE
Final changes

### ISSUE THREAD

**Issue by asselstine** [steffenix/sushi-pooltogether#10]
@steffenix I'd love to get this project finished up and pay you out.

PoolTogether bounties for projects like this are going to have a set of requirements:

- [x] A readme on how to setup and run tests
- [x] Uses Hardhat as development framework.
- [x] Uses hardhat-deploy to deploy contracts
- [x] Fork test for integration testing that is run separately from unit tests
- [x] Unit tests must have 95%+ code coverage
- [x] README must have a coverage badge (see Coveralls)
- [x] All public members documented using Natspec, with a bare minimum of @title, @notice, @param and @return

Note the unit tests requirement: a unit test is a test that can be run on a local node; i.e. using Hardhat's test infrastructure.  So that a user can simply clone the repo, run `yarn`, then run `yarn test` to ensure the code works.  Fork tests are run entirely separately, as they require more setup and are unable to isolate logic.    It's very easy to mock contracts using [Waffle](https://getwaffle.io/).  Each function needs to be isolated independently, for an example [check this out](https://github.com/pooltogether/pooltogether-pool-contracts/blob/master/test/TokenFaucet.test.js).

For our unit tests, I tend to use "real" tokens and mock interfaces, as tokens are simple enough to have implementations for.

You've completed most of these steps already; tackle the remaining items and we can finish this up!

**Comment by steffenix** [comment]
I will have a look at those tomorrow, I am still not quite sure how to do things like SushiBar without using a fork.

**Comment by asselstine** [comment]
> I am still not quite sure how to do things like SushiBar without using a fork I think I will do it by adding some interface files for testing.

Exactly; some interfaces like that simply have to be mocked using Waffle.  Fortunately you've already defined the interface, you might just need to pull it out into a separate file so that you can access it conveniently.

**Comment by steffenix** [comment]
Unit tests, coverage with badge, and documentation added.

**Comment by asselstine** [comment]
Getting closer!  Some feedback:

You've made the ETHERSCAN_TOKEN and WEB3_INFURA_PROJECT_ID environment variables public in the github workflow.  You're going to want to hide them and change them, as they will get abused.

`yarn test` should also run without setting any environment variables. The fork tests should be run using a separate command, because it's important that someone can simply clone and run tests without issue.

**Comment by steffenix** [comment]
understood I will update that.

**Comment by steffenix** [comment]
Done.

**Comment by asselstine** [comment]
LGTM 👍
