### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by asselstine** [steffenix/sushi-pooltogether#11]
Test:

1. Deposit into SushiYieldSource
2. Check balanceOfToken

balance doesn't match deposit at all

The unit tests need to be improved significantly.

1. Isolate and test each function independently.  Each function must be considered separately.  [See here](https://github.com/pooltogether/pooltogether-pool-contracts/blob/master/test/TokenFaucet.test.js).  Notice how each function is tested as independently as possible.
2. Ensure 100% code coverage for each function
3. Test mathematical edge cases for each function.

**Comment by steffenix** [comment]
I am having some issues with the mock because I can't properly simulate a deposit to xSushi, where the blanaceOf the yield source will change within the same call.
