### ISSUE TITLE
Deploy and verify!

### ISSUE THREAD

**Issue by asselstine** [steffenix/sushi-pooltogether#4]
@steffenix We're happy with how this came together.

Last piece: deploy to networks and verify on Etherscan!

Networks:
- Kovan
- Rinkeby
- mainnet!

Happy to complete the grant after.  Thank you!

**Comment by steffenix** [comment]
I can deploy to testnet, 
Right now mainnet is a bit too expensive to use

**Comment by asselstine** [comment]
Let's start with the testnets, and for mainnet just deploy to a mainnet fork.  That'll at least give us a simple deploy script to push it out to mainnet.

**Comment by steffenix** [comment]
Isn't that script what you need ?
https://www.github.com/steffenix/sushi-pooltogether/tree/master/deploy%2F00_deploy.ts

**Comment by steffenix** [comment]
https://github.com/steffenix/sushi-pooltogether/pull/5

**Comment by steffenix** [comment]
https://kovan.etherscan.io/address/0xCfEf4c2caa56408C745F638548AC08818B3d775d
https://rinkeby.etherscan.io/address/0xCfEf4c2caa56408C745F638548AC08818B3d775d

**Comment by asselstine** [comment]
@steffenix Do they work?  Are they connected to instances of SushiBar?  It appears they aren't connected to anything real

**Comment by steffenix** [comment]
They aren't, i just tried deployment, I can try to connect it if you can provide the sushi and the pooltogether addresses

**Comment by steffenix** [comment]
Kovan:

https://github.com/pooltogether/pooltogether-pool-contracts/tree/master/deployments/kovan
https://github.com/sushiswap/sushiswap/tree/master/deployments/kovan

Rinkeby:

https://github.com/sushiswap/sushiswap/tree/master/deployments/rinkeby
https://github.com/pooltogether/pooltogether-pool-contracts/tree/master/deployments/rinkeby

**Comment by steffenix** [comment]
There isn't enough liquidity on testnet to get sushi tokens

**Comment by asselstine** [comment]
You'll need to connect with the Sushi team

**Comment by steffenix** [comment]
What I had to do is deploy the sushi code myself, it wasn't possible to get some sushi from the deployed testnet.

Here you have a deposit to the PrizePool contract.
https://kovan.etherscan.io/tx/0xbc5c54bea7b47a1791f6d2d0fceb71a22a95544ffceeac40ef37633589556139


Here is the withdrawInstantlyFrom:
https://kovan.etherscan.io/tx/0x1b50b1b244ad1b615410a54a53a31c6536115c6e7d936dd3f15d654ca059e714

**Comment by asselstine** [comment]
Excellent!  That's good to see.

**Comment by asselstine** [comment]
Now, what is strange about the deployments is that they have different args than the `deploy.js` script.

Can you update the deploy.ts script so that it uses named accounts?  

That way we can simply go:

`hardhat deploy --network rinkeby`

`hardhat deploy --network kovan`

etc.

Once it's ready, I'd be happy to deploy to mainnet.  Then we can notify the Sushi team that they can start playing with it.

**Comment by steffenix** [comment]
@asselstine I am not familiar with named accounts, can you point me to the doc?

**Comment by steffenix** [comment]
ok updated @asselstine https://github.com/steffenix/sushi-pooltogether/blob/master/deploy/00_deploy.ts#L7

**Comment by asselstine** [comment]
LGTM
